#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: c1050fe
#
Name     : R-Rtsne
Version  : 0.17
Release  : 52
URL      : https://cran.r-project.org/src/contrib/Rtsne_0.17.tar.gz
Source0  : https://cran.r-project.org/src/contrib/Rtsne_0.17.tar.gz
Summary  : T-Distributed Stochastic Neighbor Embedding using a Barnes-Hut
Group    : Development/Tools
License  : BSD-4-Clause
Requires: R-Rtsne-lib = %{version}-%{release}
Requires: R-Rtsne-license = %{version}-%{release}
Requires: R-Rcpp
BuildRequires : R-Rcpp
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![CRAN
version](http://www.r-pkg.org/badges/version/Rtsne)](https://cran.r-project.org/package=Rtsne/)
[![R-CMD-check](https://github.com/jkrijthe/Rtsne/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/jkrijthe/Rtsne/actions/workflows/R-CMD-check.yaml)
[![codecov.io](https://codecov.io/github/jkrijthe/Rtsne/coverage.svg?branch=master)](https://app.codecov.io/github/jkrijthe/Rtsne?branch=master)
[![CRAN mirror
downloads](http://cranlogs.r-pkg.org/badges/Rtsne)](https://cran.r-project.org/package=Rtsne/)

%package lib
Summary: lib components for the R-Rtsne package.
Group: Libraries
Requires: R-Rtsne-license = %{version}-%{release}

%description lib
lib components for the R-Rtsne package.


%package license
Summary: license components for the R-Rtsne package.
Group: Default

%description license
license components for the R-Rtsne package.


%prep
%setup -q -n Rtsne
pushd ..
cp -a Rtsne buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702279059

%install
export SOURCE_DATE_EPOCH=1702279059
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-Rtsne
cp %{_builddir}/Rtsne/LICENSE %{buildroot}/usr/share/package-licenses/R-Rtsne/068716da2640ae2c57ca207355bd04fe9d116ea1 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/Rtsne/CITATION
/usr/lib64/R/library/Rtsne/DESCRIPTION
/usr/lib64/R/library/Rtsne/INDEX
/usr/lib64/R/library/Rtsne/LICENSE
/usr/lib64/R/library/Rtsne/Meta/Rd.rds
/usr/lib64/R/library/Rtsne/Meta/features.rds
/usr/lib64/R/library/Rtsne/Meta/hsearch.rds
/usr/lib64/R/library/Rtsne/Meta/links.rds
/usr/lib64/R/library/Rtsne/Meta/nsInfo.rds
/usr/lib64/R/library/Rtsne/Meta/package.rds
/usr/lib64/R/library/Rtsne/NAMESPACE
/usr/lib64/R/library/Rtsne/NEWS.md
/usr/lib64/R/library/Rtsne/R/Rtsne
/usr/lib64/R/library/Rtsne/R/Rtsne.rdb
/usr/lib64/R/library/Rtsne/R/Rtsne.rdx
/usr/lib64/R/library/Rtsne/help/AnIndex
/usr/lib64/R/library/Rtsne/help/Rtsne.rdb
/usr/lib64/R/library/Rtsne/help/Rtsne.rdx
/usr/lib64/R/library/Rtsne/help/aliases.rds
/usr/lib64/R/library/Rtsne/help/paths.rds
/usr/lib64/R/library/Rtsne/html/00Index.html
/usr/lib64/R/library/Rtsne/html/R.css
/usr/lib64/R/library/Rtsne/tests/testthat.R
/usr/lib64/R/library/Rtsne/tests/testthat/test_Rtsne.R
/usr/lib64/R/library/Rtsne/tests/testthat/test_neighbors.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/Rtsne/libs/Rtsne.so
/usr/lib64/R/library/Rtsne/libs/Rtsne.so.avx2
/usr/lib64/R/library/Rtsne/libs/Rtsne.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-Rtsne/068716da2640ae2c57ca207355bd04fe9d116ea1
